add springboot-wildfly first version
appuio/docs pull request #10
Opened 2017-01-05 11:11 UTC by arska

2017-01-05 12:14 UTC, tobru commented on app/springboot-wildfly.rst
> +* https://github.com/arska/springdemo
Please move to https://github.com/appuio/springdemo

2017-01-05 12:19 UTC, tobru requested changes

2017-01-05 12:19 UTC, tobru commented on app/springboot-wildfly.rst
> +We use the Maven-based source-to-image (s2i) build process for wildfly applications.
wildfly -> Wildfly (not only here...)

2017-01-05 12:19 UTC, tobru commented on app/springboot-wildfly.rst
> +
Would it make sense to add a link to https://docs.openshift.org/latest/dev_guide/templates.html for further information about templates?

2017-07-06 13:16 UTC, arska commented
Updated, please review @tobru

2017-07-12 06:59 UTC, merged