Explain Deprecation Notice
appuio/docs pull request #61
Opened 2020-02-28 15:53 UTC by chamer81

Here I have added a hint to explain the misleading deprecation notice that appears when pushing to the registry fails.

2020-02-28 15:58 UTC, bittner requested changes

2020-02-28 15:58 UTC, bittner commented on troubleshooting.rst
> +`[DEPRECATION NOTICE] registry v2 schema1 support will be removed in an upcoming release. Please contact admins of the registry.appuio.ch registry NOW to avoid future disruption. More information at
I'd suggest to use a code-block. e.g.
```rst
    .. code-block:: console

    [DEPRECATION NOTICE] registry v2 schema1 support will be removed ...
```

2020-02-28 15:58 UTC, bittner commented on troubleshooting.rst
> +If you see this notice, try checking whether your image push failed for some other reason such as your image tag
Maybe a comma before the "such as"?

2020-02-28 15:58 UTC, bittner commented on troubleshooting.rst
> +this issue: https://github.com/docker/for-linux/issues/942
I'd prefer:

> see \`issue #942 <https://github.com/docker/for-linux/issues/942>\`_ on the docker/for-linux issue tracker.

2020-02-28 16:04 UTC, bittner approved these changes

2020-02-28 16:06 UTC, bittner commented
The build fails for an unrelated reason (PyYAML package dependency needs to be updated).

2020-03-02 07:23 UTC, srueg approved these changes

2020-03-04 15:38 UTC, merged